In [7]:
import numpy as np

y_pred = [[0.2,0.2,0.2,0.2, 0.2], [0.1, 0.3, 0.1, 0.3, 0.2]]
y_pred = np.array(y_pred)

y_true = [[1,0,0,0,0], [0,1, 0,0,0]]
y_true = np.array(y_true)

from sklearn.metrics import roc_auc_score
roc_auc_score(y_true, y_pred, multi_class='ovr', average='macro')

ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

In [4]:
y_pred

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.1, 0.3, 0.1, 0.3, 0.2]])

In [12]:
import torch
from torchvision import datasets, transforms

train_loader = torch.utils.data.DataLoader(
        # 第一个参数是root dir
        datasets.MNIST('../data', train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ])),        batch_size=64, shuffle=True)


In [16]:
dir(train_loader.dataset)

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_exists',
 '_format_transform_repr',
 '_repr_indent',
 'class_to_idx',
 'classes',
 'data',
 'download',
 'extra_repr',
 'processed_folder',
 'raw_folder',
 'resources',
 'root',
 'target_transform',
 'targets',
 'test_data',
 'test_file',
 'test_labels',
 'train',
 'train_data',
 'train_labels',
 'training_file',
 'transform',
 'transforms']

In [16]:
dir(train_loader.dataset)

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_exists',
 '_format_transform_repr',
 '_repr_indent',
 'class_to_idx',
 'classes',
 'data',
 'download',
 'extra_repr',
 'processed_folder',
 'raw_folder',
 'resources',
 'root',
 'target_transform',
 'targets',
 'test_data',
 'test_file',
 'test_labels',
 'train',
 'train_data',
 'train_labels',
 'training_file',
 'transform',
 'transforms']

In [22]:
target_list = train_loader.dataset.targets.numpy()

In [24]:
unique, counts = np.unique(target_list, return_counts=True)
unique, counts

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]))

In [26]:
!ls 

README.md        b.txt            mnist.ipynb
a.txt            main.py          requirements.txt


In [40]:
import pickle
with open('y_pred.out', 'rb') as f:
    y_pred_r = pickle.load(f)

with open('y_true.out', 'rb') as f:
    y_true_r = pickle.load(f)

In [44]:
len(y_true_r)

10000

In [43]:
len(y_pred_r)

10000

In [36]:
y_pred_r[0].shape

(10,)

In [14]:
import main

y_true_onehot = [main.vectorized_result(ele).flatten() for ele in y_true]


In [15]:
y_true_onehot[0].shape

(10,)

In [16]:
y_true = pd.DataFrame(y_true_onehot)

In [37]:
y_true_r

array([7, 2, 1, ..., 4, 5, 6])

In [34]:
import pandas as pd

y_pred_pd = pd.DataFrame(y_pred_r)
y_pred_idx = y_pred_pd.idxmax( axis=1)

In [38]:
y_pred_idx

0       0
1       8
2       2
3       1
4       4
       ..
9995    6
9996    4
9997    7
9998    9
9999    5
Length: 10000, dtype: int64

In [32]:
y_pred

[array([9.9999392e-01, 1.3761964e-09, 6.1323499e-06, 3.7563025e-10,
        2.9656336e-12, 7.5129410e-13, 1.7346082e-10, 2.0749795e-08,
        6.9311676e-09, 7.0356559e-10], dtype=float32),
 array([2.2430431e-08, 3.1140543e-09, 1.7228732e-07, 8.5574584e-07,
        6.2827780e-06, 1.4936967e-07, 6.3699812e-10, 2.5861289e-11,
        9.9981409e-01, 1.7851713e-04], dtype=float32),
 array([5.1410945e-05, 1.5573606e-06, 9.2465878e-01, 3.0843566e-06,
        7.5021520e-02, 2.1128055e-06, 2.7047752e-05, 3.0640469e-05,
        1.7588370e-04, 2.7924498e-05], dtype=float32),
 array([2.3986345e-08, 9.9999523e-01, 1.8448585e-08, 1.9487847e-09,
        9.7643624e-07, 4.1311132e-09, 1.5007323e-08, 3.7529635e-06,
        7.1643200e-08, 3.4023195e-08], dtype=float32),
 array([2.5988655e-08, 1.3707944e-06, 6.8255709e-08, 1.0063518e-07,
        9.6414155e-01, 1.7750888e-06, 3.9120518e-08, 2.7400140e-06,
        4.1377258e-05, 3.5811074e-02], dtype=float32),
 array([9.9999988e-01, 2.2282055e-12, 5.44984

In [39]:
pd.crosstab(y_pred_idx, y_true_r)

col_0    0    1    2    3    4    5    6    7    8    9
row_0                                                  
0       97  110  103   95  106   71   99  112  106   91
1      116  133  119  106  117  105  109  110  107  117
2      103  124  106  125  114   88   99   87   90  101
3       91  126  113  101   93   84   89  103  107  104
4      105  121   93  102   98   92   93  107   87   85
5       83  108   90   93   64   74   83  106   89  107
6       94  102   89   93   92   94  107  107   89   83
7       95  112  120  106   99  102   92  110   91  102
8      100  105  107   92   93   77   92   87  106  110
9       96   94   92   97  106  105   95   99  102  109