In [4]:
import torch as t

In [5]:
t.Tensor(5, 3)

tensor([[ 0.0000e+00,  1.5846e+29, -6.1514e+35],
        [ 3.6902e+19,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.5846e+29, -7.5316e+35]])

In [6]:
x = t.rand(5, 3)

In [7]:
x

tensor([[0.2409, 0.5520, 0.6535],
        [0.0792, 0.9771, 0.3086],
        [0.2054, 0.6427, 0.5632],
        [0.0367, 0.3194, 0.5381],
        [0.1059, 0.6808, 0.8823]])

In [8]:
y = t.rand(5, 3)
y

tensor([[0.4228, 0.5896, 0.4088],
        [0.9190, 0.1946, 0.6055],
        [0.4908, 0.5100, 0.7571],
        [0.8902, 0.4084, 0.3646],
        [0.7064, 0.0027, 0.6981]])

In [9]:
x + y

tensor([[0.6637, 1.1416, 1.0623],
        [0.9982, 1.1716, 0.9141],
        [0.6963, 1.1526, 1.3203],
        [0.9269, 0.7278, 0.9027],
        [0.8123, 0.6834, 1.5805]])

In [10]:
x.add(y)

tensor([[0.6637, 1.1416, 1.0623],
        [0.9982, 1.1716, 0.9141],
        [0.6963, 1.1526, 1.3203],
        [0.9269, 0.7278, 0.9027],
        [0.8123, 0.6834, 1.5805]])

In [11]:
x

tensor([[0.2409, 0.5520, 0.6535],
        [0.0792, 0.9771, 0.3086],
        [0.2054, 0.6427, 0.5632],
        [0.0367, 0.3194, 0.5381],
        [0.1059, 0.6808, 0.8823]])

In [12]:
x.add_(y)

tensor([[0.6637, 1.1416, 1.0623],
        [0.9982, 1.1716, 0.9141],
        [0.6963, 1.1526, 1.3203],
        [0.9269, 0.7278, 0.9027],
        [0.8123, 0.6834, 1.5805]])

In [13]:
x

tensor([[0.6637, 1.1416, 1.0623],
        [0.9982, 1.1716, 0.9141],
        [0.6963, 1.1526, 1.3203],
        [0.9269, 0.7278, 0.9027],
        [0.8123, 0.6834, 1.5805]])

In [15]:
a = t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [17]:
b = a.numpy()
b


array([1., 1., 1., 1., 1.], dtype=float32)

In [18]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [19]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

是否支持gpu

In [23]:
t.cuda.is_available()


False

In [24]:
from torch.autograd import Variable

x = Variable(t.ones(2, 2), requires_grad=True)

In [25]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [26]:
y = x.sum()

In [27]:
y

tensor(4., grad_fn=<SumBackward0>)

In [28]:
y.grad_fn

In [29]:
y.backward()


In [31]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [32]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [33]:
x.grad.data

tensor([[1., 1.],
        [1., 1.]])

In [34]:
id(x.grad)

4789104576

In [35]:
id(x.grad.data)

4789102344

In [36]:
id(x.data)

4789100904